### ISSUE TITLE
training efficiency

### ISSUE THREAD

**Issue by HaoWenJohn** [Wang-ML-Lab/VDI#1]
hello,thx for your work.i have a problem when run TPT48 task.It takes me 20 seconds to run a epoch and more than 18s are wasted in generate_beta(__reconstruct_u_graph__),Is that a normal speed? Is there a way to accelerate it?

**Comment by shsjxzh** [comment]
Hi HaoWenJohn,

Thanks for using our code! This is normal because "generate_beta(reconstruct_u_graph)" will calculate the pairwise Wasserstein distance (W distance) between different domains. The time complexity would be O(N^2 * T(W distance)), where N is the number of domains. We suggest the following ways to accelerate the training:

1. Lower the usage frequency of "generate_beta". Currently, we generate the beta once per epoch. You can modify the code to generate it once per 2 epochs or once per 3 epochs.
2. Find ways to accelerate the W distance calculation. Our implementation uses the "sinkhorn loss" from " GeomLoss" library. We are working towards a more time-efficient solution, and you are welcome to try your hand at it as well.
3. Create your own "generate_beta" function. Essentially, "generate_beta" is an aggregation function that maps local domain indices "u" to global domain indices "beta". While we've attempted to use "average" (the most basic aggregation method) to obtain global domain indices, it does not produce the desired domain indices. You are free to design a more efficient "generate_beta" function to bypass the time-consuming W distance calculation.

Don't hesitate to reach out if you encounter any issues or have additonal questions!

**Comment by HaoWenJohn** [comment]
Thank you for your reply and look forward to your future work.
